ninety_nine_cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
end

ninety_nine_cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ninety_nine_cats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint(8)        not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper
    COLORS = %w(white black orange brown)
    SEXES = %w(M F)

    validates :birth_date, :color, :name, :sex, presence: true
    validates :color, inclusion: { in: COLORS }
    validates :sex, inclusion: { in: SEXES }

    has_many :cat_rental_requests,
        primary_key: :id,
        foreign_key: :cat_id,
        class_name: 'CatRentalRequest',
        dependent: :destroy

    def self.colors
        COLORS
    end
    
    def age
        time_ago_in_words(self.birth_date)
    end
end

ninety_nine_cats/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :bigint(8)        not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CatRentalRequest < ApplicationRecord
    STATUSES = %w(PENDING APPROVED DENIED)

    validates :start_date, :end_date, presence: true
    validates :status, presence: true, inclusion: { in: STATUSES }
    validate :does_not_overlap_approved_request

    belongs_to :cat,
        primary_key: :id,
        foreign_key: :cat_id,
        class_name: 'Cat'

    def overlapping_requests
        self.cat.cat_rental_requests
        .where(start_date: self.start_date..self.end_date)
        .where(end_date: self.start_date..self.end_date)
        .where.not(id: self.id)
    end

    def overlapping_approved_requests
        self.overlapping_requests
        .where(status: 'APPROVED')
    end

    def does_not_overlap_approved_request
        debugger
        if self.overlapping_approved_requests.exists?
            errors[:start_date, :end_date] << 'Cannot overlap with another rental!'
        end
    end
end

ninety_nine_cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ninety_nine_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
    def index
        @cats = Cat.all
        render :index
    end

    def show
        @cat = Cat.find(params[:id])
        render :show
    end

    def new
        @cat = Cat.new
        render :new
    end

    def edit
        @cat = Cat.find(params[:id])
        render :edit
    end
end

ninety_nine_cats/app/helpers/application_helper.rb
module ApplicationHelper
end

ninety_nine_cats/app/views/cats/_form.html.erb
<% if type == :new %>
    <% url = cats_url %>
<% else %>
    <% url = cat_url(cat) %>
<% end %>

<form action="<%= url %>" method="post">
    <% if type == :edit %>
        <input type="hidden" name="_method" value="patch">
    <% end %>

    <label for="name">Name </label>
    <input type="text" id="name" name="cat[name]" value="<%= cat.name %>">

    <br>

    <label for="sex">Sex 
        <input type="radio" id="m" name="cat[sex]" value="m" <%= cat.sex == "M" ? "checked" : "" %> >
        <label for="m">M</label>
        <input type="radio" id="f" name="cat[sex]" value="f" <%= cat.sex == "F" ? "checked" : "" %> >
        <label for="f">F</label>
    </label>

    <br>

    <label for="color">Color </label>
    <select id="color" name="cat[color]">
        <option value="" selected disabled>--Please choose a color--</option>
        <% Cat.colors.each do |color| %>
            <option value="<%= color %>" <%= cat.color == color ? "selected" : "" %> ><%= color.capitalize %></option>
        <% end %>
    </select>

    <br>

    <label for="birth_date">Birth Date </label>
    <input type="date" id="birth_date" name="cat[birth_date]" value="<%= cat.birth_date %>">

    <br>

    <label for="description">Description </label>
    <textarea id="description" name="cat[description]"><%= cat.description %></textarea>
</form>

ninety_nine_cats/app/views/cats/edit.html.erb
<h2>Edit <%= @cat.name %>!</h2>

<%= render 'form', cat: @cat, type: :edit %>

ninety_nine_cats/app/views/cats/index.html.erb
<h2>All the cats!</h2>

<% @cats.each do |cat| %>
    <a href="<%= cat_url(cat) %>"> <%= cat.name %> </a>
<% end %>

ninety_nine_cats/app/views/cats/new.html.erb
<h2>Add new cat!</h2>

<%= render 'form', cat: @cat, type: :new %>

ninety_nine_cats/app/views/cats/show.html.erb
<h2>Hi, I'm <%= @cat.name %></h2>

<table>
    <thead>
        <th colspan = '2'><%= @cat.name %></th>
    </thead>

    <tbody>
        <tr>
            <td>Age</td>
            <td><%= @cat.age %></td>
        </tr>
        <tr>
            <td>Color</td>
            <td><%= @cat.color %></td>
        </tr>
        <tr>
            <td>Sex</td>
            <td><%= @cat.sex %></td>
        </tr>
        <tr>
            <td>Description</td>
            <td><%= @cat.description %></td>
        </tr>
    </tbody>
</table>    

ninety_nine_cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>